spring.application.name=Back-end
spring.datasource.url=jdbc:mysql://localhost:3306/PoisePMS
spring.datasource.username=otheruser
spring.datasource.password=swordfish

spring.jpa-hibernate.ddl-auto=update
spring.jpa.show-sql=true